### ISSUE TITLE
Ionic serve show a blank page

### ISSUE THREAD

**Issue by NicholasYao** [driftyco/ionic-preview-app#31]
Hi, I have install the ionic2 by npm install ionic@beta.
but when I followed the steps provided in the README.md:
1.clone this repo: git clone git@github.com/driftyco/ionic-preview-app.git
2.cd ionic-preview-app
3.npm install
4.run ionic serve from a terminal

`E:\Cordova\ionic-preview-app>ionic serve
Running live reload server: http://localhost:35729
Watching: 0=www/**/*, 1=!www/lib/**/*
Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $`

it show me a blank page,and from the Chrome console,we can see:
`http://localhost:8100/build/js/zone.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/js/Reflect.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/js/app.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)`

Is there something I didn't to do?

**Comment by brandyscarney** [comment]
Can you run the following commands and then paste the output, please:

```
npm -v
node -v
ionic info
```

**Comment by JonDai** [comment]
@brandyscarney Hello!  I have are same error
```
http://localhost:8100/build/js/zone.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/js/Reflect.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8100/build/js/app.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
```
and my env:
```
$ npm -v  3.8.6
$ node -v  v5.11.0
$ ionic info

Your system information:
You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
OS:
Node Version: v5.11.0
```
can you help me?

**Comment by brandyscarney** [comment]
@JonDai Can you please update your CLI version to the latest:

```
npm install -g ionic@beta
```

and then compare your `package.json` file against the `ionic2-app-base` (if this is happening in your app): https://github.com/driftyco/ionic2-app-base/blob/typescript/package.json

**Comment by JonDai** [comment]
@brandyscarney Thank you! this problem has been solved.

**Comment by brandyscarney** [comment]
I'm going to close this then, please let me know if you're still having the issue @NicholasYao, thanks!

**Comment by akanbitoluwase** [comment]
Please I need your help. I have done all thats stated by still having the same error

npm -v 3.8.9

node -v v6.2.0

ionic info

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v6.2.0
Xcode version: Not installed

**Comment by Bforsyth1234** [comment]
I noticed that the code in list.ts throws a typescript error in the console. cause the bundler to not make app.js. You can see it is missing from www/build/js folder.  Go to app/pages/list/list.ts the last function itemTapped needs to be changed.


 Change the following function from:

`  itemTapped(event, item) {
    this.nav.push(ItemDetailsPage, {
      item: item
    });
  }`

To:
`  itemTapped(event, item) {
    this.navCtrl.push(ItemDetailsPage, {
      item: item
    });
  }`

**Comment by Gtanxingwen** [comment]
errro:http://localhost:8100/build/js/app.bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
C:\Users\Gtan>ionic -v
2.0.0


C:\Users\Gtan>npm -v
3.8.9

C:\Users\Gtan>node -v
v6.2.0

C:\Users\Gtan>ionic info

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
OS:
Node Version: v6.2.0
@brandyscarney  can you help me?

**Comment by Gtanxingwen** [comment]
i have solve I deleted the build folder in www , and clean up the npm cache,then it works

**Comment by europa-promatics** [comment]
test data

**Comment by europa-promatics** [comment]
no build folder in www...?

**Comment by appledev27** [comment]
Same problem for no 'www' folder, anyone help me please to solve above issue.

Failed to load resource: the server responded with a status of 404 + ionic

Using Ionic 1 - Dose not show curl 'cdvfile://localhost/persistent/character_1499169689846/avatar.jpg?t=1499172862717' 

Is this path of my image .

**Comment by TrayserCassa** [comment]
What worked for me:

I used emit in one service and it was shown up in the Linter. I got the same error after reinstall cordova and ionic, but the missing file was vector.js and main.js.
 
I removed all typescript errors and starting to ionic serve and it worked. After that I can use emit again.. 
Hope I can help.
